name = "ai-creator-protocol-website"
compatibility_date = "2024-01-01"
pages_build_output_dir = "dist"

# 生产环境配置
[env.production]
# route = "aicp.dev/*"

# 预览环境配置
[env.preview]
# route = "dev.aicp.dev/*"